version: '3.8'
services:
  pixellock:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./static/processed:/pixellock/static/processed
    restart: unless-stopped
